packages:
  - 'packages/cra-template/template'
  - 'packages/cra-template-typescript/template'
  - 'packages/cra-template-admin/template'
  - 'packages/utils'
  - 'packages/react-components'
  - 'packages/vite-template-react'
  - 'packages/vite-template-react-admin'
